/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aspire_pinyin_Pinyin */

#ifndef _Included_com_aspire_pinyin_Pinyin
#define _Included_com_aspire_pinyin_Pinyin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aspire_pinyin_Pinyin
 * Method:    getPinyin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aspire_pinyin_Pinyin_getPinyin
  (JNIEnv *, jclass, jstring);



#ifdef __cplusplus
}
#endif
#endif
